### ISSUE TITLE
Repository maintained 

### ISSUE THREAD

**Issue by VinayakGaikwad101** [SamarthTech/web-projects-2024#105]
Many projects contain .env file intact, which may result in unwanted API usage and data loss/theft. Maintainers have shown lack of collaboration and paid no heed to cross verify each PR, resulting in such bad situation. Furthermore, they aim to attract contributors by showing hacktoberfest tag, even though this repository is excluded from hacktoberfest2024. Such repositories will be reported with no further notice.

**Comment by anirban12x** [comment]
@VinayakGaikwad101 Don't you think it is the responsibility of Contributors, about checking their personal data or keys while pushing in the repo? Don't you think it is obviously not possible to check every file one by one before merging among so many projects?

Moreover our Open Odyssey 1.0 is a registered MLH event with Hacktoberfest, but due to some issues that got excluded, you can check the readme for further clarifications.

It is not your Instagram reels comment section to become cool, Maintain the decorum and ethics.
